services:
    - type: web
      name: luna-ai-server
      env: python
      buildCommand: pip install -r requirements.txt
      startCommand: python -m src.server
      envVars:
          - key: HOST
            value: 0.0.0.0
          - key: PORT
            fromService:
                type: web
                name: luna-ai-server
                property: port
      healthCheckPath: /health
