services:
    - type: web
      name: luna-ai-server
      env: python
      region: oregon  # Closest to US users
      plan: starter   # Free tier with 512MB RAM
      buildCommand: pip install -r requirements.txt
      startCommand: python -m src.server
      envVars:
          - key: HOST
            value: 0.0.0.0
          - key: PORT
            fromService:
                type: web
                name: luna-ai-server
                property: port
          - key: GOOGLE_API_KEY
            sync: false  # Set in Render dashboard
          - key: LOG_TO_FILE
            value: true
      healthCheckPath: /health
      disk:
        name: luna-data
        mountPath: /data
        sizeGB: 1
